# Generated by Django 3.2 on 2021-04-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=75)),
                ('book_author', models.CharField(max_length=30)),
                ('book_publisher', models.CharField(max_length=30)),
                ('book_genre', models.CharField(max_length=15)),
                ('avail', models.BinaryField()),
            ],
        ),
    ]
