# Generated by Django 3.2 on 2021-04-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210418_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 character ISBN number', max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
