# Generated by Django 3.2 on 2021-04-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedBooks',
            fields=[
                ('book_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='books.bookinstance')),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('a', 'Accepted'), ('r', 'Rejected'), ('p', 'Pending')], default='p', help_text='Borrow Request Status', max_length=1)),
            ],
        ),
    ]
