# Generated by Django 3.2 on 2021-04-24 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_requestedbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedbooks',
            name='requester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
            preserve_default=False,
        ),
    ]
