# Generated by Django 3.2 on 2021-04-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_requestedbooks_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedbooks',
            name='requester',
        ),
    ]
