# Generated by Django 3.2 on 2021-04-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_requestedbooks_requester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedbooks',
            old_name='book_id',
            new_name='id',
        ),
    ]
