# Generated by Django 3.2 on 2021-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_requestedbooks_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(default='A1', max_length=4, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
