# Generated by Django 3.2 on 2021-04-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='User_1', max_length=150, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
