# Generated by Django 3.2 on 2021-04-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
